// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pegawaiservice.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pegawaiservice.proto

It has these top-level messages:
	Pegawai
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Pegawai struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NamaDepan    string `protobuf:"bytes,2,opt,name=nama_depan,json=namaDepan" json:"nama_depan,omitempty"`
	NamaBelakang string `protobuf:"bytes,3,opt,name=nama_belakang,json=namaBelakang" json:"nama_belakang,omitempty"`
	Alamat       string `protobuf:"bytes,4,opt,name=alamat" json:"alamat,omitempty"`
}

func (m *Pegawai) Reset()                    { *m = Pegawai{} }
func (m *Pegawai) String() string            { return proto1.CompactTextString(m) }
func (*Pegawai) ProtoMessage()               {}
func (*Pegawai) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pegawai) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pegawai) GetNamaDepan() string {
	if m != nil {
		return m.NamaDepan
	}
	return ""
}

func (m *Pegawai) GetNamaBelakang() string {
	if m != nil {
		return m.NamaBelakang
	}
	return ""
}

func (m *Pegawai) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*Pegawai)(nil), "proto.Pegawai")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DataPegawaiService service

type DataPegawaiServiceClient interface {
	AddDataPegawai(ctx context.Context, in *Pegawai, opts ...grpc.CallOption) (*Response, error)
}

type dataPegawaiServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataPegawaiServiceClient(cc *grpc.ClientConn) DataPegawaiServiceClient {
	return &dataPegawaiServiceClient{cc}
}

func (c *dataPegawaiServiceClient) AddDataPegawai(ctx context.Context, in *Pegawai, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.DataPegawaiService/AddDataPegawai", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataPegawaiService service

type DataPegawaiServiceServer interface {
	AddDataPegawai(context.Context, *Pegawai) (*Response, error)
}

func RegisterDataPegawaiServiceServer(s *grpc.Server, srv DataPegawaiServiceServer) {
	s.RegisterService(&_DataPegawaiService_serviceDesc, srv)
}

func _DataPegawaiService_AddDataPegawai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pegawai)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPegawaiServiceServer).AddDataPegawai(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataPegawaiService/AddDataPegawai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPegawaiServiceServer).AddDataPegawai(ctx, req.(*Pegawai))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataPegawaiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataPegawaiService",
	HandlerType: (*DataPegawaiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDataPegawai",
			Handler:    _DataPegawaiService_AddDataPegawai_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pegawaiservice.proto",
}

func init() { proto1.RegisterFile("pegawaiservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0x86, 0x40,
	0x10, 0x80, 0x53, 0x4b, 0x73, 0x28, 0x83, 0x21, 0x62, 0x09, 0x02, 0xb1, 0x0e, 0x9e, 0x3c, 0xe4,
	0x13, 0x14, 0x5e, 0xba, 0xc5, 0xf6, 0x00, 0x31, 0xb6, 0x83, 0x2c, 0xe9, 0xba, 0xb8, 0x56, 0xaf,
	0x1f, 0xae, 0x2b, 0xfc, 0xa7, 0xe5, 0xfb, 0xbe, 0x85, 0x99, 0x81, 0x5b, 0xcb, 0x03, 0xfd, 0x91,
	0x76, 0xbc, 0xfc, 0xea, 0x2f, 0x6e, 0xec, 0x32, 0xaf, 0x33, 0x5e, 0xf8, 0xa7, 0xfa, 0x81, 0xec,
	0x7d, 0xcf, 0x58, 0x40, 0xac, 0x95, 0x88, 0xca, 0xa8, 0x4e, 0x64, 0xac, 0x15, 0x3e, 0x00, 0x18,
	0x9a, 0xe8, 0x53, 0xb1, 0x25, 0x23, 0xe2, 0x32, 0xaa, 0x73, 0x99, 0x6f, 0xa6, 0xdb, 0x04, 0x3e,
	0xc2, 0xb5, 0xcf, 0x3d, 0x8f, 0xf4, 0x4d, 0x66, 0x10, 0x89, 0xff, 0x71, 0xb5, 0xc9, 0xd7, 0xe0,
	0xf0, 0x0e, 0x52, 0x1a, 0x69, 0xa2, 0x55, 0x9c, 0xfb, 0x1a, 0xa8, 0x7a, 0x82, 0x4b, 0xc9, 0xce,
	0xce, 0xc6, 0x31, 0x0a, 0xc8, 0x26, 0x76, 0x8e, 0x06, 0xf6, 0xc3, 0x73, 0x79, 0xe0, 0xf3, 0x1b,
	0x60, 0x47, 0x2b, 0x85, 0x05, 0x3f, 0xf6, 0xfd, 0xb1, 0x85, 0xe2, 0x45, 0xa9, 0x93, 0x80, 0xc5,
	0x7e, 0x53, 0x13, 0xf8, 0xfe, 0x26, 0xf0, 0x31, 0xa2, 0x3a, 0xeb, 0x53, 0x6f, 0xda, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x43, 0x0f, 0xcb, 0xca, 0x0d, 0x01, 0x00, 0x00,
}
