// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pegawai.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	pegawai.proto

It has these top-level messages:
	Pegawai
	Response
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pegawai struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NamaDepan    string `protobuf:"bytes,2,opt,name=nama_depan,json=namaDepan" json:"nama_depan,omitempty"`
	NamaBelakang string `protobuf:"bytes,3,opt,name=nama_belakang,json=namaBelakang" json:"nama_belakang,omitempty"`
	Alamat       string `protobuf:"bytes,4,opt,name=alamat" json:"alamat,omitempty"`
}

func (m *Pegawai) Reset()                    { *m = Pegawai{} }
func (m *Pegawai) String() string            { return proto.CompactTextString(m) }
func (*Pegawai) ProtoMessage()               {}
func (*Pegawai) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pegawai) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pegawai) GetNamaDepan() string {
	if m != nil {
		return m.NamaDepan
	}
	return ""
}

func (m *Pegawai) GetNamaBelakang() string {
	if m != nil {
		return m.NamaBelakang
	}
	return ""
}

func (m *Pegawai) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Pegawai)(nil), "protobuf.Pegawai")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("pegawai.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xcd, 0x0a, 0x82, 0x40,
	0x10, 0x80, 0x51, 0xc3, 0x9f, 0x21, 0x3b, 0xcc, 0x21, 0xf6, 0x12, 0x88, 0x75, 0xf0, 0xd4, 0xa5,
	0x37, 0x88, 0x1e, 0x20, 0xf6, 0x05, 0x62, 0xc4, 0x49, 0x24, 0xdd, 0x5d, 0x5a, 0xa5, 0xd7, 0x8f,
	0x9d, 0xec, 0x34, 0x7c, 0xdf, 0x37, 0x30, 0x03, 0xa5, 0xe3, 0x9e, 0x3e, 0x34, 0x9c, 0xdd, 0xdb,
	0xce, 0x16, 0x73, 0x19, 0xed, 0xf2, 0xac, 0x17, 0xc8, 0xee, 0xbf, 0x84, 0x3b, 0x88, 0x87, 0x4e,
	0x45, 0x55, 0xd4, 0x24, 0x3a, 0x1e, 0x3a, 0x3c, 0x00, 0x18, 0x9a, 0xe8, 0xd1, 0xb1, 0x23, 0xa3,
	0xe2, 0x2a, 0x6a, 0x0a, 0x5d, 0x04, 0x73, 0x0b, 0x02, 0x8f, 0x50, 0x4a, 0x6e, 0x79, 0xa4, 0x17,
	0x99, 0x5e, 0x25, 0xb2, 0xb1, 0x0d, 0xf2, 0xba, 0x3a, 0xdc, 0x43, 0x4a, 0x23, 0x4d, 0x34, 0xab,
	0x8d, 0xd4, 0x95, 0xea, 0x13, 0xe4, 0x9a, 0xbd, 0xb3, 0xc6, 0x33, 0x2a, 0xc8, 0x26, 0xf6, 0x9e,
	0x7a, 0x96, 0xe3, 0x85, 0xfe, 0x63, 0x9b, 0xca, 0x9b, 0x97, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x11, 0x26, 0xb9, 0xbe, 0x00, 0x00, 0x00,
}
